Repository microsoft/vscode-java-test, pull requests merged in 2020-10, with the labels that each got.

#1074 Remove adaptive debouce from VS Code 1.50.0
  package-lock.json
  package.json
  src/codelens/MovingAverage.ts
  src/codelens/TestCodeLensProvider.ts
Labels: debt

#1071 issue fix: test name is truncated when name contains rounded bracket(s)
  src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts
  test/maven-junit4-suite/codelens.test.ts
  test/shared.ts
  test/test-projects/junit4/src/test/java/junit4/ParameterizedWithNameTest.java
Labels: bug

#1076 Check throwable when test skips in TestNG
  java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/testng/TestNGListener.java
Labels: bug

#1080 Use vmArgs in test configuration setting
  package.json
  package.nls.json
  package.nls.zh.json
  src/runConfigs.ts
  src/utils/launchUtils.ts
Labels: debt

#1066 feat: Support run tests from current file
  package.json
  package.nls.json
  package.nls.zh.json
  src/commands/runFromUri.ts
  src/constants/commands.ts
  src/extension.ts
  src/testItemModel.ts
  src/utils/commandUtils.ts
  test/gradle-junit5-suite/index.ts
  test/gradle-junit5-suite/runFromEditor.test.ts
Labels: enhancement

#1083 bugfix: Ignore error caused by request cancelled
  src/utils/commandUtils.ts
Labels: regression

#1086 ux: Update the run buttons to make them consistent with debugger
  package.json
Labels: ux

#1084 refactor: Only show migrate command when workspace has deprecated files
  package.json
  src/extension.ts
Labels: debt

#1088 fix: Initialize logger ahead of time
  src/extension.ts
Labels: bug
