Repository microsoft/vscode-java-test, pull requests merged in 2020-11, with the labels that each got.

#1089 feat: Navigate from stack trace to source
  package-lock.json
  package.json
  resources/templates/report.pug
  resources/templates/report_method_table.pug
  src/commands/testReportCommands.ts
  src/constants/commands.ts
  src/extension.ts
  src/testReportProvider.ts
  src/utils/commandUtils.ts
Labels: enhancement

#1099 ux: Adopt the new theme color API
  package-lock.json
  package.json
  resources/media/dark/error.svg
  resources/media/dark/pass.svg
  resources/media/light/error.svg
  resources/media/light/pass.svg
  src/explorer/testExplorer.ts
Labels: ux

#1100 fix: Set working directory for TestNG project
  java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchUtils.java
Labels: bug

#1107 refactor: Fix implicit any
  package-lock.json
  package.json
  src/utils/launchUtils.ts
  tsconfig.json
Labels: debt

#1110 Do not show the Test Explorer when no Java files in workspace
  package.json
  src/constants/configs.ts
  src/extension.ts
Labels: ux
