Repository microsoft/vscode-java-test, pull requests merged in 2023-03, with the labels that each got.

#1538 chore: Update dependencies
  .vscode/launch.json
  java-extension/com.microsoft.java.test.target/com.microsoft.java.test.tp.target
  java-extension/com.microsoft.java.test.target/pom.xml
  java-extension/pom.xml
  javaConfig.json
  package-lock.json
  package.json
Labels: debt, dependencies

#1541 Adding support for older testng versions
  java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/testng/TestNGListener.java
  test/test-projects/old-testng/pom.xml
  test/test-projects/old-testng/src/main/java/test/project/App.java
  test/test-projects/old-testng/src/test/java/test/project/AppTest.java
Labels: bug

#1543 fix: Stop the test session when exception happens
  java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchConfigurationDelegate.java
  java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchUtils.java
  java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/Response.java
  src/controller/testController.ts
  src/runners/baseRunner/BaseRunner.ts
  src/utils/launchUtils.ts
  test/suite/launchUtils.test.ts
Labels: bug

#1550 chore(deps): Update webpack to 5.76.2
  package-lock.json
Labels: dependencies

#1553 chore: Prepare for 0.38.2
  CHANGELOG.md
  java-extension/build-tools/pom.xml
  java-extension/com.microsoft.java.test.plugin.site/category.xml
  java-extension/com.microsoft.java.test.plugin.site/pom.xml
  java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF
  java-extension/com.microsoft.java.test.plugin/pom.xml
  java-extension/com.microsoft.java.test.runner/pom.xml
  java-extension/com.microsoft.java.test.target/pom.xml
  java-extension/pom.xml
  package-lock.json
  package.json
Labels: eng
